[[redirects]]
  from = "/404"
  to = "/"
  status=200 

[[redirects]]
  from = "/505"
  to = "/"
  status=200

[[redirects]]
  from = "/Auth"
  to = "/"
  status=200

[[redirects]]
  from = "/Chat"
  to = "/"
  status=200

[[redirects]]
  from = "/Reg"
  to = "/"
  status=200

[[redirects]]
  from = "/Settings"
  to = "/"
  status=200