[[redirects]]
  from = "/404"
  to = "/"
  status=200 

[[redirects]]
  from = "/505"
  to = "/"
  status=200

[[redirects]]
  from = "/sign-in"
  to = "/"
  status=200

[[redirects]]
  from = "/sign-up"
  to = "/"
  status=200

[[redirects]]
  from = "/settings"
  to = "/"
  status=200

[[redirects]]
  from = "/messenger"
  to = "/"
  status=200
  